// Since this page does not have getServerSideProps function it is statically
// generated by Next which means that the client is responsible of
// user's sign in logic and at the same time this means that firebase
// credentials need to be loaded on client side.

import { FormEvent } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { AuthAction, withAuthUser } from 'next-firebase-auth'
import { AuthLayout } from '@/layouts/auth/Auth'
import { useForm } from '@/hooks/useForm'

import type { ReactNode } from 'react'
import type { NextPageWithLayout } from '../_app'

import { signIn } from '@/services/firebase/auth'

const SignInPage: NextPageWithLayout = () => {
  const { email, password, handleInputChange } = useForm({
    email: '',
    password: ''
  })

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault()
    const firebaseUser = await signIn(email, password) // HACK: This is the reason why it is necessary to load firebase on the client.
    const userToken = (await firebaseUser?.getIdToken()) || 'unauthenticated'
    await fetch('/api/login', {
      body: JSON.stringify({ email, password }),
      headers: {
        'Content-Type': 'application/json',
        Authorization: userToken
      },
      method: 'POST'
    })
  }

  return (
    <>
      <Head>
        <title>Pokemon API Sign in</title>
      </Head>

      <div className="card w-96 bg-neutral shadow-2xl shadow-neutral">
        <form className="card-body gap-y-4" onSubmit={handleSubmit}>
          <h2 className="card-title">Sign In</h2>

          <input
            type="email"
            placeholder="Email "
            className="input-bordered input w-full max-w-xs"
            name="email"
            value={email}
            onChange={handleInputChange}
          />

          <input
            type="password"
            placeholder="Password "
            className="input-bordered input w-full max-w-xs"
            name="password"
            value={password}
            onChange={handleInputChange}
          />

          <div className="card-actions flex-col items-center justify-center">
            <button className="btn-primary btn-wide btn">Login</button>
            <p className="text-center text-sm">
              Don&apos;t have an account?{' '}
              <Link
                href={'/sign-up'}
                className="text-secondary hover:underline"
              >
                Sing up here
              </Link>
            </p>
          </div>
        </form>
      </div>
    </>
  )
}

SignInPage.getLayout = (page: ReactNode) => {
  return <AuthLayout>{page}</AuthLayout>
}

export default withAuthUser<{}>({
  whenAuthed: AuthAction.REDIRECT_TO_APP,
  whenUnauthedAfterInit: AuthAction.RENDER
})(SignInPage)
